### ISSUE TITLE
SQL fields should not start with an underscore

### ISSUE THREAD

**Issue by christophberger** [cheikhshift/struct-to-sql#1]
Thanks for providing this useful tool!

I noticed that all generated fields start with an underscore. This leading underscore seems to be added when converting from CamelCase to snake_case. 
Please suppress this leading underscore, or provide an option to switch the leading underscore on or off.

**Comment by cheikhshift** [comment]
I'm having trouble reproducing this, can you share more information? I did recently add a fix for this, please check and let me know.

**Comment by christophberger** [comment]
The fix works. I cannot replicate this anymore, even with the struct that I used when I observed this. 
This issue can be closed. Thanks!
