### ISSUE TITLE
Provide options for different SQL dialects

### ISSUE THREAD

**Issue by christophberger** [cheikhshift/struct-to-sql#2]
Please provide an option switch for generating the SQL statement for different SQL dialects like PostgreSQL, SQLite, or MySQL/MariaDB.

**Comment by cheikhshift** [comment]
I've made a few updates regarding this, please have a look and let me know if this is the direction you were referring to.

**Comment by christophberger** [comment]
Awesome. Yes, that's what I was thinking of. Works great. 
Thank you.
